#!/bin/sh
set -eu

case=$1
count=$2
shift 2

for i in $(seq 1 $count); do
    echo "# iteration ${i}"
    for i in "$@"; do
        echo "run $i..."
        (
            echo $i
            BUNDLE_GEMFILE=$HOME/code/puppet/Gemfile \
                          bundle exec time puppet apply "in.${case}/bench${i}.pp" 2>&1 \
                | perl -lane '
                    print $1 if /in ([0-9.]+) seconds/;
                    print $1 if /^\s+([0-9.]+) real/'
        ) | fmt | tee -a data/"$case"
    done
done
